In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import matplotlib.pyplot as plt

In [1]:
a = np.array([1,2,3,4])
print(a)
print(a.shape)
#printing the no of dimentions or rank
print(a.ndim)
#priniting the total number of elements
print(a.size)
print(np.zeros(3, dtype=np.int64))
print(np.ones(3,dtype=np.int64))
print(np.empty(2))
print(np.arange(5))
print(np.arange(2, 9, 2))
print(np.linspace(0,10, num=5))

# get unique values from an array
a=np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(np.unique(a))
unique_values, indexes = np.unique(a, return_index=True)
print(indexes)



[1 2 3 4]
(4,)
1
4
[0 0 0]
[1 1 1]
[-1.04688486e+281 -2.88947105e+039]
[0 1 2 3 4]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]


In [25]:
print(np.sort(np.empty(3)))

[5.e-324 5.e-324 5.e-324]


In [37]:
x = np.zeros((8,8), dtype=np.int64)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [41]:
y=np.ones([5,5],dtype=np.int64)
y[1:-1,1:-1] = np.zeros([3,3])
print(y)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [12]:
#sorting
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr = np.sort(arr)
print(arr)

#concatenating
arr1 = np.arange(4)
arr2 = np.arange(4,11)
print(np.concatenate((arr1,arr2)))

#Reshape
"""for reshape you need to have the same number of elements in the reshaped array as the original array"""
arr_reshape = np.arange(6)
print(arr_reshape.reshape(3,2))
print(arr_reshape.reshape(6,1))

[1 2 3 4 5 6 7 8]
[ 0  1  2  3  4  5  6  7  8  9 10]
[[0 1]
 [2 3]
 [4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [18]:
#slicing based on conditions
a= np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a<5])
five_up=(a>=5)
print(a[five_up])
evens = (a%2==0)
print(a[evens])
complex_conditions = ((a<3)|(a>7))
print(complex_conditions)
print(a[complex_conditions])

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[[ True  True False False]
 [False False False  True]
 [ True  True  True  True]]
[ 1  2  8  9 10 11 12]


In [30]:
#Arithmatic operations
a= np.array([4,7,2,1])
b = np.ones(4, dtype=int)
print(a+b)
print(a-b)
print((a+b)*(a-b))
print((a+b)/(a*b))
#sum of all the elements
print(a.sum())
#sum the elements row and column wise in a 2d matrix
b = np.array([[1,1],[2,3]])
print(b)
print(b.sum(axis=0))
print(b.sum(axis=1))

#broadcasting - multiplying an array with another array or a singular value
#converting miles to KMs
distance_miles = np.array([1,3,5])
distance_kms = 1.6*distance_miles
print(distance_kms)



[5 8 3 2]
[3 6 1 0]
[15 48  3  0]
[1.25       1.14285714 1.5        2.        ]
14
[[1 1]
 [2 3]]
[3 4]
[2 5]
[1.6 4.8 8. ]


In [38]:
#min, max,min ,prod,mean, std
data=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(data.max())
#max each row
print(data.max(axis=1))
#max each column
print(data.max(axis=0))
print(data.min())
print(data.sum())
#sum column wise
print(data.sum(axis=0))
print(data.mean())
print(data.mean(axis=0))


12
[ 4  8 12]
[ 9 10 11 12]
1
78
[15 18 21 24]
6.5
[5. 6. 7. 8.]


In [15]:
#unique Values and Counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)
#unique vals and their indexes
unique_vals, indexes = np.unique(a, return_index=True)
print(list(zip(unique_vals,indexes)))
#unique vals, indexes and their counts
unique_vals, indexes, counts = np.unique(a, return_counts=True, return_index=True)
print(list(zip(unique_vals,indexes,counts)))

# unique values on matrix and tensors 
a_2d = np.array([[1, 2, 3, 1], [1, 4, 4, 1], [2, 1, 3, 2], [1, 2, 3, 1]])
print(np.unique(a_2d))
#unique columns
print(np.unique(a_2d, axis=1))
#unique rows
print(np.unique(a_2d, axis=0))


[11 12 13 14 15 16 17 18 19 20]
[(11, 0), (12, 2), (13, 3), (14, 4), (15, 5), (16, 6), (17, 7), (18, 12), (19, 13), (20, 14)]
[(11, 0, 3), (12, 2, 2), (13, 3, 2), (14, 4, 2), (15, 5, 1), (16, 6, 1), (17, 7, 1), (18, 12, 1), (19, 13, 1), (20, 14, 1)]
[1 2 3 4]
[[1 2 3]
 [1 4 4]
 [2 1 3]
 [1 2 3]]
[[1 2 3 1]
 [1 4 4 1]
 [2 1 3 2]]


In [24]:
#transpose and reshape of matrix
data=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(data.reshape((6,2)))
print(data.T)
#flip or reverse of a np array
ar = np.arange(6)
print(np.flip(ar))
#for a 2d matrix
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
#reverse both  columns and rows if no axis specified
print(np.flip(arr_2d))
#reverse just rows
print(np.flip(arr_2d,axis=0))
#reverse just columns
print(np.flip(arr_2d,axis=1))
#REVERSE Just one column or row
arr_2d[1]=np.flip(arr_2d[1])
print(arr_2d)
arr_2d[:,1]=np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[5 4 3 2 1 0]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [31]:
#flatten and Ravel 
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a1 =a.flatten()
a1[0]=100
print(a1)
print(a)

# in ravel there is link between the source and ravel array any change one of them effect the other,
# where as in flatten it doesn't effect
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = b.ravel()
b1[0]=99
print(b1)
b[(0,0)]=111
print(b)
print(b1)

[100   2   3   4   5   6   7   8   9  10  11  12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]
[[111   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[111   2   3   4   5   6   7   8   9  10  11  12]


In [14]:
#fancy indexing
a2d=np.empty((8,4))
for i in range(8):
    a2d[i]=i
a2d
#selects rows at the given indexes in the list
a2d[[4,2,6,0]]
a2d[[-1,-3,2]]

#given two list it selects the particular elements combined by the two lists
a2d2=np.arange(32).reshape((8,4))
a2d2
a2d2[[4,1,5,7],[3,0,1,2]]
#select each row from the first list and select the corresponding element from the select list
a2d2[[1,4,5,7]][:,[1,0,3,2]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

array([[4., 4., 4., 4.],
       [2., 2., 2., 2.],
       [6., 6., 6., 6.],
       [0., 0., 0., 0.]])

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [2., 2., 2., 2.]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

array([19,  4, 21, 30])

array([[ 5,  4,  7,  6],
       [17, 16, 19, 18],
       [21, 20, 23, 22],
       [29, 28, 31, 30]])

In [34]:
#where condition in np
a2dd = np.random.rand(4,4)
np.where(a2dd>0.5,1,0)

#boolean operations
arr = np.random.randn(100)
#check values greater than 0
(arr>0).sum()
np.random.randint(0,5, size=10)

#cumulative sum of 1000 coin flips
draws = np.random.randint(0,2,size=1000)
#set 1 if its heads else -1
steps =np.where(draws>0,1,-1)
#generate cumulative values of each turn
walks = steps.cumsum()
walks
walks.min()
walks.max()
#check the first position where it reached abs 30
(np.abs(walks)>30).argmax()



array([[1, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 0, 1]])

47

array([2, 3, 2, 0, 3, 2, 2, 4, 3, 0])

array([ -1,  -2,  -3,  -2,  -3,  -4,  -3,  -4,  -3,  -2,  -1,   0,  -1,
        -2,  -3,  -4,  -5,  -4,  -3,  -4,  -3,  -2,  -1,   0,  -1,  -2,
        -1,   0,  -1,   0,   1,   0,   1,   2,   3,   2,   3,   4,   5,
         6,   7,   6,   7,   8,   7,   8,   9,   8,   7,   8,   9,   8,
         9,  10,  11,  10,   9,  10,   9,   8,   9,  10,  11,  10,  11,
        10,  11,  12,  13,  14,  15,  16,  15,  16,  15,  14,  13,  14,
        13,  12,  13,  12,  13,  12,  13,  14,  15,  14,  15,  16,  15,
        14,  15,  14,  13,  14,  13,  14,  13,  12,  13,  12,  11,  10,
        11,  12,  13,  14,  15,  14,  15,  16,  15,  14,  13,  12,  11,
        12,  13,  12,  13,  12,  11,  12,  11,  12,  11,  12,  13,  14,
        15,  14,  13,  12,  11,  10,  11,  10,  11,  10,   9,  10,   9,
        10,   9,   8,   7,   6,   5,   4,   5,   6,   5,   6,   7,   8,
         7,   6,   7,   6,   7,   6,   5,   4,   3,   4,   3,   2,   3,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  10,   

-23

23

0